name: Build README PDF
on: [push, pull_request]

jobs:
  build-pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make fonts-dejavu
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install md-to-pdf (npm)
        run: |
          npm i md-to-pdf
      - name: Create output directory
        run: |
          mkdir artifacts
      - name: Create README
        run: |
          export PATH=$(pwd)/node_modules/.bin:$PATH
          cat header_footer.md README.md RELEASES.md | md-to-pdf --config-file .gh/config.js --stylesheet .gh/markdown.css > "artifacts/README.pdf"
      - uses: actions/upload-artifact@v3
        with:
          name: readme-pdf
          path: artifacts/*

